bag_recorder_node:
  ros__parameters:
    # 記録設定
    record_all_topics: false
    topic_list: [/mux_joy, /scan]
    
    # 保存先設定
    save_directory: '/home/jetson/rosbag/'
    
    # ディスク容量閾値（GB）
    disk_space_warning_threshold_gb: 10.0
    disk_space_critical_threshold_gb: 3.0
    
    # PS3コントローラーのボタンマッピング
    button_square: 0
    button_cross: 1
    button_circle: 2
    button_triangle: 3